[server]
headless = true
enableCORS = false
enableXsrfProtection = false
[browser]
gatherUsageStats = false
[theme]
base = "dark"
primaryColor = "#fbbf24"
backgroundColor = "#0f172a"
secondaryBackgroundColor = "#1e293b"
textColor = "#e2e8f0"
